# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  toast:
    type: npm-registry
    url: "https://git.toast-server.net/api/packages/toast/npm/"
    token: ${{ secrets.GITEA_TOKEN }}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "12:00"
      timezone: "Australia/NSW"
    assignees:
    - "toast-ts"
    labels:
    - "dependencies"
    open-pull-requests-limit: 8
    rebase-strategy: auto
    registries:
    - toast
