compressionLevel: mixed
enableGlobalCache: false
progressBarStyle: "simba"
defaultSemverRangePrefix: ""
supportedArchitectures:
  os:
    - "linux"
    - "darwin"
  cpu:
    - "x64"
npmScopes:
  toast:
    npmRegistryServer: https://git.toast-server.net/api/packages/toast/npm/
