services:
  bot:
    container_name: daggerbot
    build: .
    restart: unless-stopped
    volumes:
      - ./.git:/Daggerbot/.git:rw
      - ./src/:/Daggerbot/src/:rw
      - ./dist/:/Daggerbot/dist/:rw
