services:
  cache:
    container_name: redis-cache
    image: redis/redis-stack-server:7.2.0-v6
    restart: unless-stopped
    ports:
      - 6379:6379/tcp
  db:
    container_name: postgres-db
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    volumes:
      - /var/lib/docker/volumes/daggerbot-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
