services:
  cache:
    container_name: daggerbot-redis
    image: redis/redis-stack-server:7.2.0-v10
    restart: unless-stopped
    ports:
      - 6379:6379/tcp
  db:
    container_name: daggerbot-postgres
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    ports:
      - 5432:5432/tcp
    volumes:
      - /var/lib/docker/volumes/daggerbot-db:/var/lib/postgresql/data:rw
    environment:
      #POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
